### ISSUE TITLE
Local invidious server over SSL marked as invalid - but reachable over web Invidious works

### ISSUE THREAD

**Issue by gianpo86** [lamarios/clipious#403]
I host my invidious on a server (docker) that is reachable over x.x.x.x:port on the LAN. A nginx reverse proxy in front takes care of the SSL and Invidious is reachable over domain at https://invidious.mydomain.org (only LAN) (443 as port, nginix makes the rest)

The config in the invidious API shows that the url is set properly . I can access invidious over Web.

I can also access invidious over Clipious via direct ip adress/port (changing the docker file configs)

**If I try to enter the server address in the setup page of Clipious I just get a "Invalid Server" withouth any further error message.**

SSL verification is enabled

Fresh installation of Clipious 1.17.4 on Android TV

I would like to add some logs or so, the problem is I have no idea how to get to the logs on the Android TV

**Comment by lamarios** [comment]
Is it a self sign ssl certificate ?

**Comment by gianpo86** [comment]
It is a Let’s Encrypt provided certificate, issued via Ngnix Proxy Manager and provided via .mywire.org over DynDns

**Comment by lamarios** [comment]
I've implemented a fix for better error handling when adding a server. If you know how to build a branch and use it feel free to have a try otherwise, it will be in the next release, this week end maybe.

https://github.com/lamarios/clipious/pull/405

**Comment by gianpo86** [comment]
> can you give me the content of whats in /api/v1/stats url on your server ?

{"software":{"name":"invidious","version":"2023.12.01-d76fed5","branch":"master"}}

**Comment by gianpo86** [comment]
> I've implemented a fix for better error handling when adding a server. If you know how to build a branch and use it feel free to have a try otherwise, it will be in the next release, this week end maybe.
> 
> #405

It is a matter of time :D maybe I have the time to build and install, otherwise if you are quicker I get it on the release. Many thanks for the effort!!!!

**Comment by lamarios** [comment]
> > can you give me the content of whats in /api/v1/stats url on your server ?
> 
> {"software":{"name":"invidious","version":"2023.12.01-d76fed5","branch":"master"}}

This looks correct. Even more puzzling 😅

**Comment by lamarios** [comment]
I released the app, please give it a try to we can see what's going on.

**Comment by gianpo86** [comment]
Thanks a lot for the fastest release ever 📦 !!! 
Now I am very curious to know why this issue pops up!
This is the message I get after trying to add the server:

ClientException with SocketException: No route to host (OS Error: No route to host, errno = 113), address =
invidious.mydomain.mywire.org, **port = 58504**, uri=https://invidious.mydomain.mywire.org/api/v1/stats

Of course the port is wrong I guess...

Though my docker_compose:
```
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: user
          password: pass
          host: invidious-db
          port: 5432
        check_tables: true
        captcha_enabled: false
        default_user_preferences:
          locale: de
          region: DE
        external_port: 443
        domain: invidious.mydomain.mywire.org
        hmac_key: some-key
        https_only: true
```

Why the heck does it try to connect on 58504?
